version = 0.1

[default]
[default.global.parameters]
stack_name = "little-fire-flames"

[default.build.parameters]
cached = true
parallel = true
template_file = "instance.infra.sam.yaml"

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
region = "us-east-1"

[default.package.parameters]
resolve_s3 = true

